### ISSUE TITLE
README should specify that npm3 will not work for nested dependency access

### ISSUE THREAD

**Issue by hankfanchiu** [emberjs/super-rentals#16] opened 2016-04-26 08:19 UTC
In reference to: https://github.com/levanto-financial/ember-lodash/issues/5

The README is vague on the prerequisites for this app. Directly installing Node would come with the latest npm (v3), which would not fully install every dependency required (in my case, for ember-lodash).

My workaround was to `brew install homebrew/versions/node4-lts`, which installed **npm v2.15.1**.

**Comment by toddjordan** [comment] 2016-05-12 04:48
@hankfanchiu thanks for the feedback.  I'm not entirely sure the app needs lodash.  I'll do some experimenting and see if I can remove the dependency, otherwise I'll do as you suggest.

**Comment by toddjordan** [comment] 2016-05-12 14:15
Hey, looks like we need lodash for mirage.  I was able to reproduce the issue using npm 3.  Adding a note in the readme

**Comment by toddjordan** [comment] 2016-05-12 14:57
Ok, tried this out with the latest versions of ember and it now works with npm3.  See PR #20  for a reference of what I updated.

Closing this issue when the PR gets merged.

**Comment by toddjordan** [comment] 2016-05-12 15:10
Merged PR, closing

**Closed by toddjordan** 2016-05-12 15:10 UTC

**Comment by hankfanchiu** [comment] 2016-05-23 06:03
Awesome, thanks for looking into it @toddjordan
